In [1]:
from keras import models
from keras import layers

network = models.Sequential()

Using TensorFlow backend.


This initializes an empty net that we can start adding layers to.
We progress as follows to build a network that can learn a function, which we know already, should be close to<br>
>   <x,y> --> <x+y,x-y>

First an input layer; see the (highly incomplete, sic!) documentation at https://keras.io/layers/core/

In [2]:
network.add(layers.Dense(2, activation='sigmoid', use_bias=True, input_shape=(2,)))

A Dense layer is a standard one which is connected to all nodes in the layer before and after (incl. here to the implicit input layer).<br>
The first argument, here given as 2, indicates the number of nodes (or neurons) in the hidden layer.
The input_shape argument is more cryptic. For now, we are satisfied by knowing that
> input_shape=(2,)

specifies a that this layer, and thus this network, takes 2 inputs (the apparently misplaced comma is correct Python syntax (sic!)).<br>
Notice in the documentation and the textbook, the word "Kernel" is used for the collection (more precisely: matrix) of weights. Setting use_bias=True adds an additional constant weigth as we have seen in the lecture (and the excerpt of Mitchell's book).<br>
A list of activation functions can be found here: https://keras.io/activations/<br>
<br>
So far we have built a network which, according to standard terminology, has two input nodes and three hidden nodes.<br>
The last added layer will be the output layer, so to complete it with an output layer with two nodes, we do as follows.

In [3]:
network.add(layers.Dense(2, activation='linear'))

The activation function 'linear' is a misnomer, it refers to the identity function, in other words it means no activation function.<br>
But now we have completed or network, and the next step is to configure the training which is done in the "compile" function, which takes three arguments:
> <i>optimizer</i>: corresponds to the backpropagation algorithm, and Keras a collection of variants; a stub of documentation is available at https://keras.io/optimizers/; see the example below of how an optimizer is created and used<br>
<i>loss</i>: what we have referred to as the error function; independently of what it is called, it is the function that will attempted minimized during training<br>
> <i>metrics</i>: a bit unclear if it has any influence on the training process; it is explained as a measurement that each monitored during training (unclear if monitoring here means 'printed out' or something more). Most examples in the textbook uses  <tt>metrics=['accuracy']</tt>, so we do that here.
Unfortunately, the textbook and the Keras documentation do not give a definition of accuracy (sic!).

In [4]:
from keras import optimizers
sgd = optimizers.SGD(lr=0.01,  momentum=0.1)
network.compile(optimizer =sgd, loss='mean_squared_error', metrics=['accuracy'])

The <tt>SGD</tt> type of optimizer stands for  seems to be closest to the traditional backpropagation; its <tt>lr</tt> parameter stands for learning rate, and <tt>momentum</tt> is what it says;  (the documentation mentions other possible arguments, some are more obvious than others).<p>
Now comes the difficult part, reading in the input data from a file (sic!)<br>
The following assumes that we have the file backPropTraining.csv in the working directory.
By a bit of guessing and arbitrary searching, the following code was put together

In [5]:
from numpy import genfromtxt
all_data = genfromtxt('backPropTraining.csv', delimiter=',')
inputs = all_data[:,(0,1)]
outputs = all_data[:,(2,3)]

Try the following to test that things look right

In [6]:
all_data

array([[-0.8 , -0.9 , -1.7 ,  0.1 ],
       [ 0.53,  0.43,  0.96,  0.1 ],
       [ 0.63, -0.96, -0.33,  1.59],
       ...,
       [-0.4 , -0.17, -0.57, -0.23],
       [ 0.21,  0.83,  1.04, -0.62],
       [ 0.01,  0.72,  0.73, -0.71]])

In [7]:
inputs

array([[-0.8 , -0.9 ],
       [ 0.53,  0.43],
       [ 0.63, -0.96],
       ...,
       [-0.4 , -0.17],
       [ 0.21,  0.83],
       [ 0.01,  0.72]])

In [8]:
outputs

array([[-1.7 ,  0.1 ],
       [ 0.96,  0.1 ],
       [-0.33,  1.59],
       ...,
       [-0.57, -0.23],
       [ 1.04, -0.62],
       [ 0.73, -0.71]])

To follow good practice, we split the data set into two parts, training and validation:

In [9]:
training_inputs = inputs[0:699,:]
validation_inputs = inputs[700:999,:]
training_outputs = outputs[0:699,:]
validation_outputs = outputs[700:999,:]

In [10]:
network.fit(inputs, outputs, epochs=100)

Epoch 1/100
1000/1000 [==============================] - 0s 54us/step - loss: 0.7722 - accuracy: 0.4910
Epoch 2/100
1000/1000 [==============================] - 0s 14us/step - loss: 0.7485 - accuracy: 0.4980
Epoch 3/100
1000/1000 [==============================] - 0s 15us/step - loss: 0.7321 - accuracy: 0.6370
Epoch 4/100
1000/1000 [==============================] - 0s 14us/step - loss: 0.7194 - accuracy: 0.7920
Epoch 5/100
1000/1000 [==============================] - 0s 15us/step - loss: 0.7084 - accuracy: 0.8150
Epoch 6/100
1000/1000 [==============================] - 0s 14us/step - loss: 0.6978 - accuracy: 0.8420
Epoch 7/100
1000/1000 [==============================] - 0s 14us/step - loss: 0.6878 - accuracy: 0.8510
Epoch 8/100
1000/1000 [==============================] - 0s 15us/step - loss: 0.6784 - accuracy: 0.8530
Epoch 9/100
1000/1000 [==============================] - 0s 17us/step - loss: 0.6692 - accuracy: 0.8700
Epoch 10/100
1000/1000 [==============================] - 0s 17u

1000/1000 [==============================] - 0s 15us/step - loss: 0.2410 - accuracy: 0.9860
Epoch 80/100
1000/1000 [==============================] - 0s 16us/step - loss: 0.2367 - accuracy: 0.9860
Epoch 81/100
1000/1000 [==============================] - 0s 15us/step - loss: 0.2323 - accuracy: 0.9860
Epoch 82/100
1000/1000 [==============================] - 0s 14us/step - loss: 0.2278 - accuracy: 0.9860
Epoch 83/100
1000/1000 [==============================] - 0s 15us/step - loss: 0.2233 - accuracy: 0.9860
Epoch 84/100
1000/1000 [==============================] - 0s 14us/step - loss: 0.2187 - accuracy: 0.9850
Epoch 85/100
1000/1000 [==============================] - 0s 14us/step - loss: 0.2141 - accuracy: 0.9860
Epoch 86/100
1000/1000 [==============================] - 0s 15us/step - loss: 0.2094 - accuracy: 0.9860
Epoch 87/100
1000/1000 [==============================] - 0s 15us/step - loss: 0.2046 - accuracy: 0.9850
Epoch 88/100
1000/1000 [==============================] - 0s 15us/st

Continue from here on you own:
<ul>
	<li>Test the trained model on the validation data; can you see any signs of over training?</li>
    <li>Generate plots that shows how fast the training converges; you may copy-paste some lines from the 3.5-classifying-movie-reviewsCORRECTED-BY-HC.ipynb notebook</li>
	<li>Try to vary the training set-up in different ways to see the effect on the results (loss, accuracy, overtraining, speed of convergence:
       <ul>
	     <li>Different number of nodes in the hidden layer</li>
	     <li>With and without bias and with momentum of different magnitudea (for each of the different number of nodes in the hidden layer)</li>
	     <li>Try to add more hidden layers to see the effect</li>
	     <li>Try out different activation functions as well as different optimizers and loss functions
           (you will probably not know what they exactly mean, but try them anyhow to see if they are useful and perhaps try to find out more about them)</li>
       </ul>
    </li>
	<li>Find a mathematical expression that defines the sort of "accuracy" that Keras (and our textbook) applies. You teachers searches for a good answer resulted in useless references into some weird Python code.
    </li>

</ul>
